USE vk_insight;

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS first_name VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS last_name VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS age INT NULL,
  ADD COLUMN IF NOT EXISTS sex TINYINT NULL,
  ADD COLUMN IF NOT EXISTS city VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS education_level TEXT NULL,
  ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NULL,
  ADD COLUMN IF NOT EXISTS posts_recent TINYINT(1) NULL;
