version: '3.8'

services:
  mc-integration:
    image: mc-integration:latest
    container_name: mc-integration
    ports:
      - "8089:8089"
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=redis
      - STORAGE_S3_ENDPOINT=http://minio:9000
      - STORAGE_ACCESS_KEY_ID=miniominio
      - STORAGE_SECRET_KEY=miniominio
      - STORAGE_S3_BUCKET_NAME=newbucket
      - SECURITY_AUTH_PATH=http://mc-authenticate:8091
    networks:
      - social-network
    restart: unless-stopped

networks:
  social-network:
    driver: bridge