version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: fastdelivery-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tariffdb
      POSTGRES_USER: fastuser
      POSTGRES_PASSWORD: fastpass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
