services:
  ms-eureka:
    container_name: ms-eureka
    image: ms-eureka
    ports:
      - "8761:8761"

  ms-friend:
    container_name: ms-friend
    image: ms-friend
    ports:
      - "8084:8084"
    environment:
      # === Spring Profile ===
      - SPRING_PROFILES_ACTIVE=dev
      # !!! DEV OPTIONS - work only if the Spring Profile switched to DEV !!!
      - APP_AUTH_SERVICE_ENABLED=false # false выключает валидацию JWT и запускает FakeAuthServiceClient
      - APP_ACCOUNT_SERVICE_ENABLED=false # false выключает AccountServiceClient и запускает FakeAccountServiceClient
      - APP_RECOMMENDATION_SERVICE_ENABLED=false # false выключает сервис рекомендаций и запускает FakeRecommendationService
      # !!! PRODUCTION OPTIONS !!!
      # === Feign: Authentication Service ===
      - FEIGN_AUTH_SERVICE_NAME=mc-authentication # подключение по name, приоритет ниже, чем подключение по URL
      - FEIGN_AUTH_SERVICE_URL=http://mc-authentication:8081 # подключение по URL, приоритет выше, чем подключение по name
      # === Feign: Account Service ===
      - FEIGN_ACCOUNT_SERVICE_NAME=mc-account # подключение по name, приоритет ниже, чем подключение по URL
      - FEIGN_ACCOUNT_SERVICE_URL=http://mc-account:8088 # подключение по URL, приоритет выше, чем подключение по name
      # === Kafka ===
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-broker:9092
      # === Postgres ===
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/friend_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      # === Liquibase ===
      - SPRING_LIQUIBASE_CHANGE_LOG=classpath:db/changelog/changelog-master.yaml
      # === Eureka ===
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://ms-eureka:8761/eureka/
      # === Kafka Publisher Emergency ===
      - KAFKA_PUBLISHER_EMERGENCY_MAX_ATTEMPTS=5
      - KAFKA_PUBLISHER_EMERGENCY_FIXED_DELAY=180000 # 180000 = 3 minutes
      - KAFKA_PUBLISHER_EMERGENCY_BATCH_SIZE=20 # 20
      - KAFKA_PUBLISHER_EMERGENCY_TIMEOUT=5 # seconds
      # === Outbox Cleanup Scheduler ===
      - OUTBOX_CLEANUP_RETENTION_DAYS=3 # частота очистки outbox с KafkaMessages
    depends_on:
      - postgres-db

  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    container_name: frontend
    image: rumyancevivan/frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - postgres-db
      - ms-eureka

  ms-gateway:
    container_name: ms-gateway
    image: ms-gateway
    ports:
      - "8765:8080"
    depends_on:
      - ms-eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://ms-eureka:8761/eureka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka-broker:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-broker
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092,PLAINTEXT_INTERNAL://kafka-broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"