services:
  ms-friend:
    container_name: ms-friend
    ports:
      - "8084:8084"
    image: ${DOCKER_IMAGE}
    environment:
      # === Spring Profile ===
      - SPRING_PROFILES_ACTIVE=prod
      # === Feign: Authentication Service ===
      - FEIGN_AUTH_SERVICE_NAME=mc-authentication # подключение по name, приоритет ниже, чем подключение по URL
      - FEIGN_AUTH_SERVICE_URL=http://mc-authentication:8081 # подключение по URL, приоритет выше, чем подключение по name
      # === Feign: Account Service ===
      - FEIGN_ACCOUNT_SERVICE_NAME=mc-account # подключение по name, приоритет ниже, чем подключение по URL
      - FEIGN_ACCOUNT_SERVICE_URL=http://mc-account:8088 # подключение по URL, приоритет выше, чем подключение по name
      # === Kafka ===
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-broker:9092
      # === Postgres ===
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/friend_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      # === Liquibase ===
      - SPRING_LIQUIBASE_CHANGE_LOG=classpath:db/changelog/changelog-master.yaml
      # === Eureka ===
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE=http://ms-eureka:8761/eureka/
      # === Kafka Publisher Emergency ===
      - KAFKA_PUBLISHER_EMERGENCY_MAX_ATTEMPTS=5
      - KAFKA_PUBLISHER_EMERGENCY_FIXED_DELAY=180000 # 180000 = 3 minutes
      - KAFKA_PUBLISHER_EMERGENCY_BATCH_SIZE=20 # 20
      - KAFKA_PUBLISHER_EMERGENCY_TIMEOUT=5 # seconds
      # === Outbox Cleanup Scheduler ===
      - OUTBOX_CLEANUP_RETENTION_DAYS=3 # частота очистки outbox с KafkaMessages
    networks:
      - infrastructure_social-network

networks:
  infrastructure_social-network:
    external: true