server:
  port: ${SERVER_PORT:8081}

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://127.0.0.1:${DB_PORT:5432}/social_network
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      fail-fast: true
    properties:
      request.timeout.ms: 3000
      default.api.timeout.ms: 3000
      connections.max.idle.ms: 5000
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: post-service-smoke
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  kafka:
    topic:
      post: social.post.events
      comment: social.comment.events
      reaction: social.reaction.events
      partitions: 3
      replicas: 1

security:
  authenticate:
    url: ${SECURITY_AUTH_URL:http://localhost:8091}
    path: ${SECURITY_AUTH_PATH:/api/v1/auth/validate}

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.apache.kafka: INFO
    org.springframework.kafka: DEBUG

management:
  health:
    kafka:
      enabled: true
  endpoint:
    health:
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,info